### ISSUE TITLE
Add new rule to default rules array

### ISSUE THREAD

**Issue by aguidis** [M6Web/php-cs-fixer-config#11]
I just would like to know if there is a way to add a custom rule to the default array of rules (defined in `M6Web\CS\Config\php71::getRules()`)

**Comment by lucascourot** [comment]
Hi,

They are not "default" rules but our own rules we apply internally for our projects.

I think it's better you create your own config and use ours as an example.

If you really really want to "extend" our config you can always inject it in yours and merge your config with it.

**Comment by Oliboy50** [comment]
This question seems to have been answered.
