### ISSUE TITLE
[Pool] phpDoc annotation without dot

### ISSUE THREAD

**Issue by jb-reynaud** [M6Web/php-cs-fixer-config#2]
## Pourquoi
Sondage pour évoluer la config actuelle du paramètre `phpdoc_annotation_without_dot`.

## Explication 
Le paramètre oblige ou non toutes les annotations **qui ne sont pas des commentaires** à ne pas avoir de point à la fin (même si il y a une description).
Aujourd'hui la valeur de ce paramètre est à **true**, hérité de la conf `symfony`.

#### Avec true, voici les modifs:
```diff
public class Dog
{
   /**
    * Un super commentaire important.
    * 
-   * @param string $food de la bonne nourriture.
+   * @param string $food de la bonne nourriture
    * 
-   * @throws dogException une superbe exception.
+   * @throws dogException une superbe exception
    */
   public function eat(string $food)
   {
   }
}
```
#### Alors ... 
On vote:
:+1: je veux rester sur true, pas de point à la fin des annotations **(valeur actuelle)**
:neutral_face:  pas d'importance.
:-1: je veux des points partout!

**Comment by b-viguier** [comment]
Il me semble qu'on s'était dit que ça ferait beaucoup de modifications pour pas grand chose de forcer le `.` final.

**Comment by lucascourot** [comment]
à ne pas confondre avec `phpdoc_summary` que j'ai désactivé et qui lui s'occupe des ponctuations de la description de la phpdoc et non des descriptions des annotations

**Comment by jb-reynaud** [comment]
## Conclusion
victoire de :+1: => pas de modif
