### ISSUE TITLE
[Pool] blank line after opening tag

### ISSUE THREAD

**Issue by jb-reynaud** [M6Web/php-cs-fixer-config#3]
## Pourquoi
Sondage pour évoluer la config actuelle du paramètre `blank_line_after_opening_tag`.

## Explication 
Avoir une ligne ou non après le tag `<?php`.
Aujourd'hui la valeur de ce paramètre est à **true**, hérité de la conf `symfony`.

#### Avec true, voici les modifs:
```diff
<?php
+ // new line added
namespace M6/Blabla;
```
#### Alors ... 
On vote:
:+1: je veux rester sur true, on force une ligne vide entre `<?php` et le code **(valeur actuelle)**
:neutral_face:  pas d'importance.
:-1:  surtout pas de ligne!

**Comment by Meroje** [comment]
A savoir parceque c'est pas documenté, cette règle s'applique sur les fichiers qui ne contiennent **que** du php https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3e41a5319700566a2e6886ca464720c7d195e28a/src/Fixer/PhpTag/BlankLineAfterOpeningTagFixer.php#L62

**Comment by Oliboy50** [comment]
merci @jb-reynaud d'avoir pris le temps de créer ces sondages, c'est super smart 👍 

par contre je pensais vraiment pas qu'une telle règle de lint existait... du coup, ça m'fait penser à [une chanson](https://www.youtube.com/watch?v=XoDY9vFAaG8) 😄

**Comment by jb-reynaud** [comment]
Je cloture => victoire du 👍 => pas de mofif!
